### ISSUE TITLE
cannot visit

### ISSUE THREAD

**Issue by 227BaronChen** [jaswindersingh2/SPOT-RNA2#1]
I cannot visit the web "https://www.dropbox.com/s/"

**Comment by 227BaronChen** [comment]
![image](https://user-images.githubusercontent.com/61997568/126280783-b98d6849-2288-48a7-bcd9-7c5ea105d3d1.png)

**Comment by jaswindersingh2** [comment]
Dropbox doesn't work in few countries. Please try the following link to download SPOT-RNA2 checkpoints:

https://app.nihaocloud.com/f/fbf3315a91d542c0bdc2/

Jaswinder

**Comment by 227BaronChen** [comment]
> Dropbox doesn't work in few countries. Please try the following link to download SPOT-RNA2 checkpoints:
> 
> https://app.nihaocloud.com/f/fbf3315a91d542c0bdc2/
> 
> Jaswinder

Is there any other download path? I can’t access the download path you provided.
